config/routes.rb
Rails.application.routes.draw do

	root 'pages#home'

  get '/home', to: 'pages#home'

  #get '/recipes', to: 'recipes#index'
  #get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  #post '/recipes', to: 'recipes#create'
  #get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  #patch '/recipes/:id', to: 'recipes#update'
  #get '/recipes/:id', to: 'recipes#show', as:'recipe'
  #delete '/recipes/:id', to: 'recipes#destroy'

  #con resources se hacen las mismas rutas que arriba automaticamente
  resources :recipes do
    member do 
      post 'like'
    end
  end

  resources :chefs, except: [:new, :destroy]

  get '/register', to: 'chefs#new'

  #necesario para el login
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  
end

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>Bienvenido a las recetas de la familia Hernández Mondragón</h1>

	<h2>
		Esta página esta hecha para ir guardando nuestras recetas familiares.
	</h2>

	<%= link_to "¡Crea tu cuenta aquí!", register_path, class: "btn btn-lg btn-success" %>
</div>

<div class="row">
	<div class="col-lg-4">
		<h3 class="midraw">
			Ver las recetas como invitado solamente
		</h3>
		<h2 class="left">Navega por las recetas sin necesidad de tener una cuenta creada</h2>
		<p><%= link_to "Ver recetas", recipes_path, class: "btn btn-warning btn-small"%></p>
	</div>

	<div class="col-lg-4">
		<h3 class="midraw">
			¡Ingresa a tu cuenta Chef!
		</h3>
		<h2 class="left">Si ya tienes una cuenta puedes crear/editar tus recetas, ver las de otros Chefs y más.</h2>
		<p><%= link_to "Acceder a tu cuenta", login_path, class: "btn btn-warning btn-small"%></p>
	</div>

	<div class="col-lg-4">
		<h3 class="midraw">
			Este es un espacio extra, aún sin servicio
		</h3>
		<h2 class="left">Si tienes una idea para usar este espacio dime</h2>
		<p><%= link_to "Botón sin lugar a donde ir :(", "", class: "btn btn-warning btn-small"%></p>
	</div>
</div>